# Display a box
print("Please enter a character for the eye: ",end="")
x = input()
print("                 ################")
print("                 #" +f"   {x}    {x}"+"     #" )
print("                 #              #")
print("                 ################")
print("         ###########################")
print("         #                         #")
print("         #                         #")
print("         #                         #")
print("   #     #                         #")
print("   #######                         #")
print("   #     #                         #")
print("         #                         #")
print("         #                         #")
print("         #                         #")
print("         ###########################")
print("         #     #              #    #")
print("         #     #              #    #")
print("         #     #              #    #")
print("         #     #              #    #")
print("         #     #              #    #")
print("         #     #              #    #")
print("         #     #              #    #")
print("         #######              ######")